version: '3'
services:
  backend-api:
    container_name: backend-api
    image: backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - app-network

  frontend-web:
    container_name: frontend-web
    image: frontend
    ports:
      - "80:80"
    depends_on:
      - backend-api
    networks:
      - app-network
      
  etl-fandit:
    container_name: etl-fandit
    build:
      context: ./etl-fandit
    volumes:
      - ./etl-fandit/output:/app/output
      - ./etl-fandit/logs:/app/logs
    environment:
      - TZ=Europe/Madrid
      - ENABLE_AUTO_ETL=false  # Cambiar a "true" para activar la ejecución automática
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge