version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fandit-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME:-fandit_db}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_PORT: 3306
    depends_on:
      - db
    networks:
      - fandit-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME:-fandit_db}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USER:-fandit_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - fandit-network

networks:
  fandit-network:
    driver: bridge

volumes:
  mysql_data: