version: '3.8'

services:
  backend-api:
    container_name: backend-api
    image: backend:latest
    environment:
      - PORT=8000
    # ports:
    #   - "8000:8000" # Para Swagger, peticiones Postman o curl.
    networks:
      - app-network

  frontend-web:
    container_name: frontend-web
    image: frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend-api
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
