version: '3.8'

services:
  # 🔹 Backend API
  backend-api:
    container_name: backend-api
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=8000
    networks:
      - app-network

  # 🔹 Frontend con Nginx
  frontend-web:
    container_name: frontend-web
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Se accede al frontend en http://localhost:8080/
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro  # Se monta la configuración de Nginx
      - ./frontend/dist:/usr/share/nginx/html  # Asegurar que la build de Vite está en el contenedor
    depends_on:
      - backend-api
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
